import enum


class NotificationPriority(str, enum.Enum):
    NORMAL = "NORMAL"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class NotificationType(str, enum.Enum):
    NEW_APPOINTMENT = "NEW_APPOINTMENT"
    APPOINTMENT_CANCELLED = "APPOINTMENT_CANCELLED"
    APPOINTMENT_RESCHEDULED = "APPOINTMENT_RESCHEDULED"
    PATIENT_CHECKED_IN = "PATIENT_CHECKED_IN"
    PAYMENT_PENDING = "PAYMENT_PENDING"
    QUEUE_ENQUEUE_FAILED = "QUEUE_ENQUEUE_FAILED"
    APPOINTMENT_NO_SHOW = "APPOINTMENT_NO_SHOW"
    LAB_REPORT_READY = "LAB_REPORT_READY"
    LAB_REPORT_UPDATED = "LAB_REPORT_UPDATED"
    LAB_ORDER_CREATED = "LAB_ORDER_CREATED"
    LAB_ORDER_CANCELLED = "LAB_ORDER_CANCELLED"
    PRESCRIPTION_CREATED = "PRESCRIPTION_CREATED"
    PRESCRIPTION_UPDATED = "PRESCRIPTION_UPDATED"
    EMERGENCY_ALERT = "EMERGENCY_ALERT"
    ADMIN_UPDATE = "ADMIN_UPDATE"
    HANDOVER_TAKEN_OVER = "HANDOVER_TAKEN_OVER"
    SHIFT_UPDATED = "SHIFT_UPDATED"
    IPD_ADMITTED = "IPD_ADMITTED"


class SourceModule(str, enum.Enum):
    OPD_BILLING = "OPD_BILLING"
    LAB = "LAB"
    RECEPTIONIST = "RECEPTIONIST"
    NURSE = "NURSE"
    PHARMACY = "PHARMACY"
    ADMIN = "ADMIN"
    SYSTEM = "SYSTEM"
    IPD = "IPD"


class ReferenceType(str, enum.Enum):
    APPOINTMENT = "APPOINTMENT"
    LAB_ORDER = "LAB_ORDER"
    PRESCRIPTION = "PRESCRIPTION"
    BILL = "BILL"
    PATIENT = "PATIENT"
    USER = "USER"
    SCHEDULE = "SCHEDULE"
    LEAVE = "LEAVE"
    HANDOVER = "HANDOVER"
    ALERT = "ALERT"
    ADMISSION = "ADMISSION"
