import enum


class NotificationPriority(str, enum.Enum):
    NORMAL = "NORMAL"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class NotificationType(str, enum.Enum):
    NEW_APPOINTMENT = "NEW_APPOINTMENT"
    APPOINTMENT_CANCELLED = "APPOINTMENT_CANCELLED"
    APPOINTMENT_RESCHEDULED = "APPOINTMENT_RESCHEDULED"
    PATIENT_CHECKED_IN = "PATIENT_CHECKED_IN"
    LAB_REPORT_READY = "LAB_REPORT_READY"
    LAB_REPORT_UPDATED = "LAB_REPORT_UPDATED"
    PRESCRIPTION_CREATED = "PRESCRIPTION_CREATED"
    PRESCRIPTION_UPDATED = "PRESCRIPTION_UPDATED"
    EMERGENCY_ALERT = "EMERGENCY_ALERT"
    ADMIN_UPDATE = "ADMIN_UPDATE"


class SourceModule(str, enum.Enum):
    OPD_BILLING = "OPD_BILLING"
    LAB = "LAB"
    RECEPTIONIST = "RECEPTIONIST"
    NURSE = "NURSE"
    PHARMACY = "PHARMACY"
    ADMIN = "ADMIN"
    SYSTEM = "SYSTEM"


class ReferenceType(str, enum.Enum):
    APPOINTMENT = "APPOINTMENT"
    LAB_ORDER = "LAB_ORDER"
    PRESCRIPTION = "PRESCRIPTION"
    BILL = "BILL"
    PATIENT = "PATIENT"
    USER = "USER"
    SCHEDULE = "SCHEDULE"
    LEAVE = "LEAVE"
