"""remove old tables

Revision ID: 0fd72e123992
Revises: r6s7t8u9v0w2
Create Date: 2026-07-15 18:00:28.546744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0fd72e123992'
down_revision: Union[str, Sequence[str], None] = 'r6s7t8u9v0w2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_doctor_leaves_doctor_id'), table_name='doctor_leaves')
    op.drop_index(op.f('ix_doctor_leaves_end_date'), table_name='doctor_leaves')
    op.drop_index(op.f('ix_doctor_leaves_id'), table_name='doctor_leaves')
    op.drop_index(op.f('ix_doctor_leaves_start_date'), table_name='doctor_leaves')
    op.drop_table('doctor_leaves')
    op.drop_index(op.f('ix_specializations_id'), table_name='specializations')
    op.drop_table('specializations')
    op.drop_index(op.f('ix_doctor_schedules_day_of_week'), table_name='doctor_schedules')
    op.drop_index(op.f('ix_doctor_schedules_doctor_id'), table_name='doctor_schedules')
    op.drop_index(op.f('ix_doctor_schedules_id'), table_name='doctor_schedules')
    op.drop_table('doctor_schedules')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_priority'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_source_module'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_created'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_unread'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_doctor_queue_next_requests_appointment_id'), table_name='doctor_queue_next_requests')
    op.drop_index(op.f('ix_doctor_queue_next_requests_doctor_id'), table_name='doctor_queue_next_requests')
    op.drop_index(op.f('ix_doctor_queue_next_requests_id'), table_name='doctor_queue_next_requests')
    op.drop_index(op.f('ix_doctor_queue_next_requests_queue_id'), table_name='doctor_queue_next_requests')
    op.drop_index(op.f('ix_doctor_queue_next_requests_request_date'), table_name='doctor_queue_next_requests')
    op.drop_table('doctor_queue_next_requests')
    op.drop_table('hospital_settings')
    op.add_column('appointments', sa.Column('appointment_uid', sa.String(), nullable=False))
    op.add_column('appointments', sa.Column('department_id', sa.Integer(), nullable=False))
    op.add_column('appointments', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('appointments', sa.Column('symptoms', sa.Text(), nullable=True))
    op.add_column('appointments', sa.Column('diagnosis', sa.Text(), nullable=True))
    op.add_column('appointments', sa.Column('follow_up_date', sa.Date(), nullable=True))
    op.add_column('appointments', sa.Column('appointment_type', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('created_by', sa.Integer(), nullable=True))
    op.alter_column('appointments', 'reason',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('appointments', 'notes',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_unique_constraint(None, 'appointments', ['appointment_uid'])
    op.create_foreign_key(None, 'appointments', 'patients', ['patient_id'], ['id'])
    op.create_foreign_key(None, 'appointments', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'appointments', 'departments', ['department_id'], ['id'])
    op.drop_column('appointments', 'appointment_date')
    op.drop_column('appointments', 'updated_at')
    op.drop_column('appointments', 'appointment_time')
    op.drop_column('appointments', 'patient_name')
    op.drop_index(op.f('ix_doctor_profiles_employee_id'), table_name='doctor_profiles')
    op.create_unique_constraint(None, 'doctor_profiles', ['employee_id'])
    op.add_column('opd_visits', sa.Column('appointment_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_opd_visits_appointment_id'), 'opd_visits', ['appointment_id'], unique=False)
    op.create_foreign_key(None, 'opd_visits', 'appointments', ['appointment_id'], ['id'])
    op.drop_constraint(op.f('receptionist_profiles_user_id_key'), 'receptionist_profiles', type_='unique')
    op.drop_index(op.f('ix_receptionist_profiles_user_id'), table_name='receptionist_profiles')
    op.create_index(op.f('ix_receptionist_profiles_user_id'), 'receptionist_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receptionist_profiles_user_id'), table_name='receptionist_profiles')
    op.create_index(op.f('ix_receptionist_profiles_user_id'), 'receptionist_profiles', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('receptionist_profiles_user_id_key'), 'receptionist_profiles', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'opd_visits', type_='foreignkey')
    op.drop_index(op.f('ix_opd_visits_appointment_id'), table_name='opd_visits')
    op.drop_column('opd_visits', 'appointment_id')
    op.drop_constraint(None, 'doctor_profiles', type_='unique')
    op.create_index(op.f('ix_doctor_profiles_employee_id'), 'doctor_profiles', ['employee_id'], unique=True)
    op.add_column('appointments', sa.Column('patient_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('appointment_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('appointment_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='unique')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.alter_column('appointments', 'notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('appointments', 'reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('appointments', 'created_by')
    op.drop_column('appointments', 'appointment_type')
    op.drop_column('appointments', 'follow_up_date')
    op.drop_column('appointments', 'diagnosis')
    op.drop_column('appointments', 'symptoms')
    op.drop_column('appointments', 'scheduled_at')
    op.drop_column('appointments', 'department_id')
    op.drop_column('appointments', 'appointment_uid')
    op.create_table('hospital_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('tagline', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('address_line1', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('address_line2', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('pincode', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('gstin', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('pan', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('registration_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('default_registration_fee', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('default_consultation_fee', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('default_gst_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('timezone', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('hospital_settings_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('hospital_settings_pkey'))
    )
    op.create_table('doctor_queue_next_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('queue_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('request_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('requested_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('handled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('handled_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('doctor_queue_next_requests_appointment_id_fkey')),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name=op.f('doctor_queue_next_requests_doctor_id_fkey')),
    sa.ForeignKeyConstraint(['handled_by'], ['users.id'], name=op.f('doctor_queue_next_requests_handled_by_fkey')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('doctor_queue_next_requests_patient_id_fkey')),
    sa.ForeignKeyConstraint(['queue_id'], ['patient_queue.id'], name=op.f('doctor_queue_next_requests_queue_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('doctor_queue_next_requests_pkey'))
    )
    op.create_index(op.f('ix_doctor_queue_next_requests_request_date'), 'doctor_queue_next_requests', ['request_date'], unique=False)
    op.create_index(op.f('ix_doctor_queue_next_requests_queue_id'), 'doctor_queue_next_requests', ['queue_id'], unique=False)
    op.create_index(op.f('ix_doctor_queue_next_requests_id'), 'doctor_queue_next_requests', ['id'], unique=False)
    op.create_index(op.f('ix_doctor_queue_next_requests_doctor_id'), 'doctor_queue_next_requests', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_queue_next_requests_appointment_id'), 'doctor_queue_next_requests', ['appointment_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notification_type', postgresql.ENUM('NEW_APPOINTMENT', 'APPOINTMENT_CANCELLED', 'APPOINTMENT_RESCHEDULED', 'PATIENT_CHECKED_IN', 'LAB_REPORT_READY', 'LAB_REPORT_UPDATED', 'PRESCRIPTION_CREATED', 'PRESCRIPTION_UPDATED', 'EMERGENCY_ALERT', 'ADMIN_UPDATE', 'HANDOVER_TAKEN_OVER', 'SHIFT_UPDATED', name='notificationtype'), autoincrement=False, nullable=False),
    sa.Column('priority', postgresql.ENUM('NORMAL', 'HIGH', 'CRITICAL', name='notificationpriority'), autoincrement=False, nullable=False),
    sa.Column('source_module', postgresql.ENUM('OPD_BILLING', 'LAB', 'RECEPTIONIST', 'NURSE', 'PHARMACY', 'ADMIN', 'SYSTEM', name='sourcemodule'), autoincrement=False, nullable=False),
    sa.Column('reference_type', postgresql.ENUM('APPOINTMENT', 'LAB_ORDER', 'PRESCRIPTION', 'BILL', 'PATIENT', 'USER', 'SCHEDULE', 'LEAVE', 'HANDOVER', 'ALERT', name='referencetype'), autoincrement=False, nullable=False),
    sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('notifications_created_by_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_index(op.f('ix_notifications_user_unread'), 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_created'), 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_source_module'), 'notifications', ['source_module'], unique=False)
    op.create_index(op.f('ix_notifications_priority'), 'notifications', ['priority'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_table('doctor_schedules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('day_of_week', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shift_start', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('shift_end', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('consultation_duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name=op.f('doctor_schedules_doctor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('doctor_schedules_pkey'))
    )
    op.create_index(op.f('ix_doctor_schedules_id'), 'doctor_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_doctor_schedules_doctor_id'), 'doctor_schedules', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_schedules_day_of_week'), 'doctor_schedules', ['day_of_week'], unique=False)
    op.create_table('specializations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('specializations_department_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('specializations_pkey'))
    )
    op.create_index(op.f('ix_specializations_id'), 'specializations', ['id'], unique=False)
    op.create_table('doctor_leaves',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('leave_type', postgresql.ENUM('leave', 'holiday', name='doctorleavetype'), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name=op.f('doctor_leaves_doctor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('doctor_leaves_pkey'))
    )
    op.create_index(op.f('ix_doctor_leaves_start_date'), 'doctor_leaves', ['start_date'], unique=False)
    op.create_index(op.f('ix_doctor_leaves_id'), 'doctor_leaves', ['id'], unique=False)
    op.create_index(op.f('ix_doctor_leaves_end_date'), 'doctor_leaves', ['end_date'], unique=False)
    op.create_index(op.f('ix_doctor_leaves_doctor_id'), 'doctor_leaves', ['doctor_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('actor_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('actor_role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('resource_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('audit_logs_actor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    # ### end Alembic commands ###
"""remove old tables

Revision ID: 0fd72e123992
Revises: r6s7t8u9v0w2
Create Date: 2026-07-15 18:00:28.546744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0fd72e123992'
down_revision: Union[str, Sequence[str], None] = 'r6s7t8u9v0w2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_doctor_leaves_doctor_id'), table_name='doctor_leaves')
    op.drop_index(op.f('ix_doctor_leaves_end_date'), table_name='doctor_leaves')
    op.drop_index(op.f('ix_doctor_leaves_id'), table_name='doctor_leaves')
    op.drop_index(op.f('ix_doctor_leaves_start_date'), table_name='doctor_leaves')
    op.drop_table('doctor_leaves')
    op.drop_index(op.f('ix_specializations_id'), table_name='specializations')
    op.drop_table('specializations')
    op.drop_index(op.f('ix_doctor_schedules_day_of_week'), table_name='doctor_schedules')
    op.drop_index(op.f('ix_doctor_schedules_doctor_id'), table_name='doctor_schedules')
    op.drop_index(op.f('ix_doctor_schedules_id'), table_name='doctor_schedules')
    op.drop_table('doctor_schedules')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_priority'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_source_module'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_created'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_unread'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_doctor_queue_next_requests_appointment_id'), table_name='doctor_queue_next_requests')
    op.drop_index(op.f('ix_doctor_queue_next_requests_doctor_id'), table_name='doctor_queue_next_requests')
    op.drop_index(op.f('ix_doctor_queue_next_requests_id'), table_name='doctor_queue_next_requests')
    op.drop_index(op.f('ix_doctor_queue_next_requests_queue_id'), table_name='doctor_queue_next_requests')
    op.drop_index(op.f('ix_doctor_queue_next_requests_request_date'), table_name='doctor_queue_next_requests')
    op.drop_table('doctor_queue_next_requests')
    op.drop_table('hospital_settings')
    op.add_column('appointments', sa.Column('appointment_uid', sa.String(), nullable=False))
    op.add_column('appointments', sa.Column('department_id', sa.Integer(), nullable=False))
    op.add_column('appointments', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('appointments', sa.Column('symptoms', sa.Text(), nullable=True))
    op.add_column('appointments', sa.Column('diagnosis', sa.Text(), nullable=True))
    op.add_column('appointments', sa.Column('follow_up_date', sa.Date(), nullable=True))
    op.add_column('appointments', sa.Column('appointment_type', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('created_by', sa.Integer(), nullable=True))
    op.alter_column('appointments', 'reason',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('appointments', 'notes',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_unique_constraint(None, 'appointments', ['appointment_uid'])
    op.create_foreign_key(None, 'appointments', 'patients', ['patient_id'], ['id'])
    op.create_foreign_key(None, 'appointments', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'appointments', 'departments', ['department_id'], ['id'])
    op.drop_column('appointments', 'appointment_date')
    op.drop_column('appointments', 'updated_at')
    op.drop_column('appointments', 'appointment_time')
    op.drop_column('appointments', 'patient_name')
    op.drop_index(op.f('ix_doctor_profiles_employee_id'), table_name='doctor_profiles')
    op.create_unique_constraint(None, 'doctor_profiles', ['employee_id'])
    op.add_column('opd_visits', sa.Column('appointment_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_opd_visits_appointment_id'), 'opd_visits', ['appointment_id'], unique=False)
    op.create_foreign_key(None, 'opd_visits', 'appointments', ['appointment_id'], ['id'])
    op.drop_constraint(op.f('receptionist_profiles_user_id_key'), 'receptionist_profiles', type_='unique')
    op.drop_index(op.f('ix_receptionist_profiles_user_id'), table_name='receptionist_profiles')
    op.create_index(op.f('ix_receptionist_profiles_user_id'), 'receptionist_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receptionist_profiles_user_id'), table_name='receptionist_profiles')
    op.create_index(op.f('ix_receptionist_profiles_user_id'), 'receptionist_profiles', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('receptionist_profiles_user_id_key'), 'receptionist_profiles', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'opd_visits', type_='foreignkey')
    op.drop_index(op.f('ix_opd_visits_appointment_id'), table_name='opd_visits')
    op.drop_column('opd_visits', 'appointment_id')
    op.drop_constraint(None, 'doctor_profiles', type_='unique')
    op.create_index(op.f('ix_doctor_profiles_employee_id'), 'doctor_profiles', ['employee_id'], unique=True)
    op.add_column('appointments', sa.Column('patient_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('appointment_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('appointment_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='unique')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.alter_column('appointments', 'notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('appointments', 'reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('appointments', 'created_by')
    op.drop_column('appointments', 'appointment_type')
    op.drop_column('appointments', 'follow_up_date')
    op.drop_column('appointments', 'diagnosis')
    op.drop_column('appointments', 'symptoms')
    op.drop_column('appointments', 'scheduled_at')
    op.drop_column('appointments', 'department_id')
    op.drop_column('appointments', 'appointment_uid')
    op.create_table('hospital_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('tagline', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('address_line1', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('address_line2', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('pincode', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('gstin', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('pan', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('registration_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('default_registration_fee', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('default_consultation_fee', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('default_gst_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('timezone', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('hospital_settings_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('hospital_settings_pkey'))
    )
    op.create_table('doctor_queue_next_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('queue_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('request_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('requested_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('handled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('handled_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('doctor_queue_next_requests_appointment_id_fkey')),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name=op.f('doctor_queue_next_requests_doctor_id_fkey')),
    sa.ForeignKeyConstraint(['handled_by'], ['users.id'], name=op.f('doctor_queue_next_requests_handled_by_fkey')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('doctor_queue_next_requests_patient_id_fkey')),
    sa.ForeignKeyConstraint(['queue_id'], ['patient_queue.id'], name=op.f('doctor_queue_next_requests_queue_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('doctor_queue_next_requests_pkey'))
    )
    op.create_index(op.f('ix_doctor_queue_next_requests_request_date'), 'doctor_queue_next_requests', ['request_date'], unique=False)
    op.create_index(op.f('ix_doctor_queue_next_requests_queue_id'), 'doctor_queue_next_requests', ['queue_id'], unique=False)
    op.create_index(op.f('ix_doctor_queue_next_requests_id'), 'doctor_queue_next_requests', ['id'], unique=False)
    op.create_index(op.f('ix_doctor_queue_next_requests_doctor_id'), 'doctor_queue_next_requests', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_queue_next_requests_appointment_id'), 'doctor_queue_next_requests', ['appointment_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notification_type', postgresql.ENUM('NEW_APPOINTMENT', 'APPOINTMENT_CANCELLED', 'APPOINTMENT_RESCHEDULED', 'PATIENT_CHECKED_IN', 'LAB_REPORT_READY', 'LAB_REPORT_UPDATED', 'PRESCRIPTION_CREATED', 'PRESCRIPTION_UPDATED', 'EMERGENCY_ALERT', 'ADMIN_UPDATE', 'HANDOVER_TAKEN_OVER', 'SHIFT_UPDATED', name='notificationtype'), autoincrement=False, nullable=False),
    sa.Column('priority', postgresql.ENUM('NORMAL', 'HIGH', 'CRITICAL', name='notificationpriority'), autoincrement=False, nullable=False),
    sa.Column('source_module', postgresql.ENUM('OPD_BILLING', 'LAB', 'RECEPTIONIST', 'NURSE', 'PHARMACY', 'ADMIN', 'SYSTEM', name='sourcemodule'), autoincrement=False, nullable=False),
    sa.Column('reference_type', postgresql.ENUM('APPOINTMENT', 'LAB_ORDER', 'PRESCRIPTION', 'BILL', 'PATIENT', 'USER', 'SCHEDULE', 'LEAVE', 'HANDOVER', 'ALERT', name='referencetype'), autoincrement=False, nullable=False),
    sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('notifications_created_by_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_index(op.f('ix_notifications_user_unread'), 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_created'), 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_source_module'), 'notifications', ['source_module'], unique=False)
    op.create_index(op.f('ix_notifications_priority'), 'notifications', ['priority'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_table('doctor_schedules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('day_of_week', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shift_start', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('shift_end', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('consultation_duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name=op.f('doctor_schedules_doctor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('doctor_schedules_pkey'))
    )
    op.create_index(op.f('ix_doctor_schedules_id'), 'doctor_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_doctor_schedules_doctor_id'), 'doctor_schedules', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_schedules_day_of_week'), 'doctor_schedules', ['day_of_week'], unique=False)
    op.create_table('specializations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('specializations_department_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('specializations_pkey'))
    )
    op.create_index(op.f('ix_specializations_id'), 'specializations', ['id'], unique=False)
    op.create_table('doctor_leaves',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('leave_type', postgresql.ENUM('leave', 'holiday', name='doctorleavetype'), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name=op.f('doctor_leaves_doctor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('doctor_leaves_pkey'))
    )
    op.create_index(op.f('ix_doctor_leaves_start_date'), 'doctor_leaves', ['start_date'], unique=False)
    op.create_index(op.f('ix_doctor_leaves_id'), 'doctor_leaves', ['id'], unique=False)
    op.create_index(op.f('ix_doctor_leaves_end_date'), 'doctor_leaves', ['end_date'], unique=False)
    op.create_index(op.f('ix_doctor_leaves_doctor_id'), 'doctor_leaves', ['doctor_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('actor_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('actor_role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('resource_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('audit_logs_actor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    # ### end Alembic commands ###